version: '3'
services:
  todo-api:
    build: .
    container_name: todo_api_app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules  # Untuk memastikan volume node_modules terpisah dari volume host
    ports:
      - "9000:3000"
    restart: 'always'
    env_file:
      - .env  # Pastikan file .env ada di root proyek
    environment:
      - DB_CONNECTION=$DB_CONNECTION
      - DB_HOST=$DB_HOST  # Gunakan nama service postgres untuk komunikasi antar container
      - DB_PORT=$DB_PORT
      - DB_NAME=$DB_NAME
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_READ_CONNECTION=$DB_READ_CONNECTION
      - DB_READ_HOST=$DB_READ_HOST
      - DB_READ_PORT=$DB_READ_PORT
      - DB_READ_NAME=$DB_READ_NAME
      - DB_READ_USERNAME=$DB_READ_USERNAME
      - DB_READ_PASSWORD=$DB_READ_PASSWORD
      - API_NINJA_KEY=$API_NINJA_KEY
      - API_NINJA_URL=$API_NINJA_URL
      - HASHJWT=$HASHJWT

#   postgres:
#     image: postgres:15
#     container_name: postgres15
#     environment:
#       POSTGRES_DB: $DB_NAME  # Gunakan variabel DB_NAME dari .env
#       POSTGRES_USER: $DB_USERNAME  # Gunakan variabel DB_USERNAME dari .env
#       POSTGRES_PASSWORD: $DB_PASSWORD  # Gunakan variabel DB_PASSWORD dari .env
#     ports:
#       - "5432:5432"  # Agar database dapat diakses di port 5432
#     volumes:
#       - postgres_data:/var/lib/postgresql/data  # Menyimpan data secara persisten

# # Volume untuk menyimpan data PostgreSQL secara persisten
# volumes:
#   postgres_data:
